OnlineShoppingSystem/OnlineShoppingSystem/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineShoppingSystem.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }
        [Display(Name ="Product Name")]
        public string ProductName { get; set; }
        [Display(Name = "Price")]
        public int ProductPrice { get; set; }
        public string ProductSize{ get; set; }
        public string ProductColor { get; set; }
        [Display(Name ="Picture")]
        public byte[] ProductPic { get; set; }
        public virtual Department Department { get; set; }
        [ForeignKey("Department")]
        public int DepartmentId { get; set; }
        [ForeignKey("CartId")]
        public ICollection<CartItem> CartItems { get; set; }
        [ForeignKey("SupplierCode")]
        public ICollection<SuppliedItem> SuppliedItems { get; set; }
    }
}

OnlineShoppingSystem/OnlineShoppingSystem/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingSystem.Models;

namespace OnlineShoppingSystem.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index()
        {
            return View(db.Orders.ToList());
        }

        [Authorize(Roles = "Customer")]
        public ActionResult CreateOrder()
        {
            var customerId = db.Customers.Where(j => j.CustomerEmail == User.Identity.Name).Select(o => o.CustomerId).FirstOrDefault();
            var itemCount = db.CartItems.Where(k => k.CustomerId == customerId && k.OrderId == 0).Select(k => k.CartQuantity).ToList();
            if (itemCount.Count == 0)
            {
                ViewBag.CartItemsNo = 0;
            }
            else
            {
                ViewBag.CartItemsNo = itemCount.Count();
            }
            
            var cartProducts = db.CartItems.Where(k => k.CustomerId == customerId && k.OrderId == 0).Include(p => p.Product);
            OrderCartList orderCartList = new OrderCartList();
            orderCartList.CartList = cartProducts.ToList();

            return View(orderCartList);
        }

        [HttpPost]
        public JsonResult CreateOrder(string DestinationAddress)
        {
            var customerId = db.Customers.Where(j => j.CustomerEmail == User.Identity.Name).Select(o => o.CustomerId).FirstOrDefault();
            var cartList = db.CartItems.Where(l => l.CustomerId == customerId && l.OrderId == 0).ToList();
            var totalPrice = 0;
            foreach(var item in cartList)
            {
                totalPrice += item.Product.ProductPrice * item.CartQuantity;
            }

            Order order = new Order();
            order.CustomerId = customerId;
            order.DestinationAddress = DestinationAddress;
            order.TotalAmount = totalPrice;
            order.RefNo ='#'+ Guid.NewGuid().ToString().Substring(0, 10);
            order.OrderStatus = "Order Processed";
            order.ExpectedArrivalDate = DateTime.Now.AddDays(10).ToString("MM/dd/yyyy");
            db.Orders.Add(order);
            db.SaveChanges();

            foreach(var item in cartList)
            {
                item.OrderId = order.OrderId;
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
            }

            return new JsonResult { Data = new { status = true, url = Url.Action("Create", "Payment",new { orderId=order.OrderId,customerId=customerId,totAmount=order.TotalAmount}) } };
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Track(int id)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,AmountPaid,TotalAmount,DestinationAddress")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order orderItem)
        {
            Order order = db.Orders.Find(orderItem.OrderId);
            if (ModelState.IsValid)
            {
                order.OrderStatus = orderItem.OrderStatus;
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShoppingSystem/OnlineShoppingSystem/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingSystem.Models;

namespace OnlineShoppingSystem.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
       // [Authorize(Roles = "Customer")]
        // GET: Products
        public ActionResult Index()
        {
            var userName = db.Customers.Where(u => u.CustomerEmail == User.Identity.Name).Select(k => k.CustomerName).FirstOrDefault();
            ViewBag.CustomerName = userName;
            var customerId = db.Customers.Where(j => j.CustomerEmail == User.Identity.Name).Select(o => o.CustomerId).FirstOrDefault();
            var itemCount= db.CartItems.Where(k => k.CustomerId == customerId && k.OrderId == 0).Select(k => k.CartQuantity).ToList();
            if (itemCount.Count==0)
            {
                ViewBag.CartItemsNo = 0;
            }
            else
            {
                ViewBag.CartItemsNo = itemCount.Count();
            }
          

            var products = db.Products.Include(p => p.Department);
            return View(products.ToList());
        }
        [Authorize(Roles ="Customer")]
        public ActionResult CartItemsList()
        {
            var customerId = db.Customers.Where(j => j.CustomerEmail == User.Identity.Name).Select(o => o.CustomerId).FirstOrDefault();
            var itemCount= db.CartItems.Where(k => k.CustomerId == customerId && k.OrderId == 0).Select(k => k.CartQuantity).ToList();
            if (itemCount.Count==0)
            {
                ViewBag.CartItemsNo = 0;
            }
            else
            {
                ViewBag.CartItemsNo = itemCount.Count();
            }
           

            var cartProducts = db.CartItems.Where(k => k.CustomerId == customerId && k.OrderId == 0).Include(p => p.Product);
            return View(cartProducts.ToList());
        }

        [HttpPost]
        [Authorize(Roles ="Customer")]
        public JsonResult SaveCartItems(CartItem cartItem)
        {
            var customerId = db.Customers.Where(j => j.CustomerEmail == User.Identity.Name).Select(o => o.CustomerId).FirstOrDefault();
             var existCartItem= db.CartItems.Where(l => l.CustomerId == customerId && l.ProductId == cartItem.ProductId && l.OrderId == 0).FirstOrDefault();
            
            if (existCartItem == null)
            {
                cartItem.CustomerId = customerId;
                cartItem.OrderId = 0;
                db.CartItems.Add(cartItem);
                db.SaveChanges();
            }
            else
            {
                existCartItem.CartQuantity += cartItem.CartQuantity;
                db.Entry(existCartItem).State = EntityState.Modified;
                db.SaveChanges();
            }

            if (cartItem.CartId > 0||existCartItem.CartQuantity>0)
            {
                ViewBag.CartItemsNo = db.CartItems.Where(k => k.CustomerId == customerId && k.OrderId == 0).Select(k => k.CartQuantity).Count();
                return new JsonResult { Data = new { status = true,url=Url.Action("Index") } };
            }

            return new JsonResult { Data = new { status = false } };
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        
        [Authorize(Roles="admin")]
        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude  = "ProductPic")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.ProductPic = getFileById("ProductPic");
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName", product.DepartmentId);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName", product.DepartmentId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductName,ProductPrice,DepartmentId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "DepartmentName", product.DepartmentId);
            return View(product);
        }

        private byte[] getFileById(string id)
        {
            byte[] fileData = null;
            HttpPostedFileBase poImgFile = Request.Files[id];

            using (var binary = new BinaryReader(poImgFile.InputStream))
            {
                fileData = binary.ReadBytes(poImgFile.ContentLength);
            }

            return fileData;
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShoppingSystem/OnlineShoppingSystem/Views/Products/CartItemsList - Copy.cshtml
@model IEnumerable<OnlineShoppingSystem.Models.CartItem>

@{
    ViewBag.Title = "Index";
}

<h2>My Cart Items</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th style="background-color: #B8DBFD;border: 1px solid #ccc">
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
        <th style="background-color: #B8DBFD;border: 1px solid #ccc">
            @Html.DisplayNameFor(model => model.Product.ProductPrice)
        </th>
        <th style="background-color: #B8DBFD;border: 1px solid #ccc">
            @Html.DisplayNameFor(model => model.CartQuantity)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="width:120px;border: 1px solid #ccc">
                @Html.DisplayFor(modelItem => item.Product.ProductName)
            </td>
            <td style="width:120px;border: 1px solid #ccc">
                @Html.DisplayFor(modelItem => item.Product.ProductPrice)
            </td>
            <td style="width:120px;border: 1px solid #ccc">
                @Html.DisplayFor(modelItem => item.CartQuantity)
            </td>
            
        </tr>
    }
    
    @if (Model.Count()==0) {
    
        <label>No Items here</label>
    }
</table>

OnlineShoppingSystem/OnlineShoppingSystem/Views/Products/Create.cshtml
@model OnlineShoppingSystem.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>New Product</h2>

@using (Html.BeginForm(Html.BeginForm("Create", "Products", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProductSize, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductSize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductSize, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProductColor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductColor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductColor, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
       @Html.LabelFor(model => model.ProductPic, htmlAttributes: new { @class = "control-label col-md-2" })

        <input type="file" required name="ProductPic" id="ProductPic" />

    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentId, "DepartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineShoppingSystem/OnlineShoppingSystem/Views/Products/Delete.cshtml
@model OnlineShoppingSystem.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineShoppingSystem/OnlineShoppingSystem/Views/Products/Details.cshtml
@model OnlineShoppingSystem.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineShoppingSystem/OnlineShoppingSystem/Views/Products/Index.cshtml
@model IEnumerable<OnlineShoppingSystem.Models.Product>

@{
    Layout = null;
    ViewBag.Title = "Index";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Online Shopping</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/Content/Shopping/assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/Shopping/css/styles.css" rel="stylesheet" />
</head>
<style>
    div.gallery {
        margin: 1px;
        border: 2px solid #ccc;
        float: left;
        width: 17%;
    }

        div.gallery:hover {
            border: 1px solid #777;
        }

        div.gallery img {
            width: 100%;
            height: auto;
        }

    div.desc {
        padding: 15px;
        text-align: center;
    }

 
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">Online Shopping</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index","Home")">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                @if (User.IsInRole("Customer"))
                {
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Orders")">My Orders</a></li>
                }
                @if (User.IsInRole("admin"))
                {
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Departments")">Departments</a></li>
                }
                @if (User.IsInRole("admin"))
                {
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Products")">Products</a></li>
                }
                @if (User.IsInRole("admin"))
                {
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Orders")">Order Management</a></li>
                }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="@Url.Action("Index","Products")">All Products</a></li>
                        </ul>
                    </li>
                </ul>
            @if (User.IsInRole("Customer"))
            {
                <form class="d-flex">
                    <button class="btn btn-outline-dark" type="submit">
                      <a href="@Url.Action("CartItemsList")">  <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill">@ViewBag.CartItemsNo</span>
                        </a>
                    </button>

                </form>
            }
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<h2>Products</h2>

<p>
   @if (User.IsInRole("admin"))
   {
    <!-- Product actions-->
    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href='@Url.Action("Create")'>Create</a></div>
    </div>
   }
</p>



<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

            @foreach (var item in Model)
            {

                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->

                        @{
                            if (item.ProductPic != null)
                            {
                                var base64 = Convert.ToBase64String(item.ProductPic);
                                var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
                                <a href='@Url.Action("Details", new { id = item.ProductId })'>
                                    <img class="card-img-top" src='@imgsrc' />
                                </a>
                                //<div class="desc">  @Html.DisplayFor(modelItem => item.ProductPrice)</div>
                                //@Html.DisplayFor(modelItem => item.ItemDesciption)
                            }
                        }
                        @* <img class="card-img-top" src="~/Content/Shopping/assets/download (1).jpg" alt="..." />*@
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">@Html.DisplayFor(m => item.ProductName)</h5>
                                <!-- Product price-->
                                R @Html.DisplayFor(m => item.ProductPrice)
                            </div>
                        </div>
                        <!-- Product actions-->
                       @if (User.IsInRole("Customer"))
                       {
                        <button type="button" id="myBtn"  onclick="ModalData(@item.ProductId)" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
                            Add to Cart
                        </button>
                       }
                    </div>
                </div>

                            }
        </div>
    </div>
</section>

<!-- Button trigger modal -->
<!--<button type="button" id="myBtn" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
    Launch demo modal
</button>-->

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Please enter quantity</h5>
                <button type="button" id="closeIcon" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                   <label>Quantity</label>
                    <div class="col-md-10">
                        <input type="number" name="CartQuantity" placeholder="Quantity..." class="form-first-name form-control" id="CartQuantity">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="closeBtn"class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="saveBtn"  class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="~/Content/Shopping/js/scripts.js"></script>
@*<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>*@
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-1.9.0.min.js"></script>
<script>
    var productId = 0;
    var btn = document.getElementById('myBtn')
    var saveBtn = document.getElementById('saveBtn')
    var closebtn = document.getElementById('closeBtn')
    var closeIcon = document.getElementById('closeIcon')
    var modal = document.getElementById('exampleModalCenter')
    //btn.onclick = function () { $('#exampleModalCenter').modal('show'); }
    closeBtn.onclick = function () { $('#exampleModalCenter').modal('hide'); }
    closeIcon.onclick = function () { $('#exampleModalCenter').modal('hide'); }

    function ModalData(id) {

        var data = {
            ProductId: id,
            CartQuantity: 1
        }
        SaveCart(data);
    }

    $('#saveBtn').click(function () {
        var data = {
            ProductId: productId,
            CartQuantity: 1
        }

        SaveCart(data);
    })

    function SaveCart(data) {
        $.ajax({//Ajax is used for to call controller to get and post data.
            type: 'POST',
            url: '/Products/SaveCartItems', //Call Controller
            data: data,
            success: function (data) {
                if (data.status) {
                    console.log('Done')
                    alert('Successfully saved!');
                    window.location = data.url;
                }
                else {
                    console.log('Failed')
                    alert('Failed to Save!');
                }
            },
            error: function () {
                alert('Failed to Save!');
            }
        })
    }
</script>